FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements_api.txt ./
RUN pip install --no-cache-dir -r requirements_api.txt

COPY ApiTradu.py ./

EXPOSE 5000
CMD ["python", "ApiTradu.py"]
